# Make rules for configuration files.
#
# $Id$

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-i686.config $(CFG)-i686-debug.config \
	$(CFG)-i686-PAE.config $(CFG)-i686-PAEdebug.config \
	$(CFG)-x86_64.config $(CFG)-x86_64-debug.config \
	$(CFG)-s390x.config \
	$(CFG)-ppc.config $(CFG)-ppc-smp.config \
	$(CFG)-ppcnf.config $(CFG)-ppcnf-debug.config \
	$(CFG)-ppc476.config \
	$(CFG)-ppc64.config $(CFG)-ppc64p7.config $(CFG)-ppc64-debug.config 

PLATFORMS	= x86 x86_64 powerpc powerpc32 powerpc64 s390x
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp *-merged

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config config-*-merged

config-%-merged:
	@if [ -f $$(basename $@ -merged)-rhel ]; then \
		perl merge.pl $$(basename $@ -merged)-rhel $$(basename $@ -merged) >$@; \
	else \
		cp $$(basename $@ -merged) $@; \
	fi
	@if [ -f $$(basename $@ -merged)-mcp ]; then \
		perl merge.pl $$(basename $@ -merged)-mcp $@ >$@-mcp; \
		mv $@-mcp $@; \
	fi

temp-generic: config-generic-merged
	cat config-generic-merged config-nodebug > temp-generic

temp-debug-generic: config-generic-merged
	cat config-generic-merged config-debug > temp-debug-generic

temp-arm-generic: config-arm-generic-merged temp-generic
	perl merge.pl $^ > $@

temp-armv7-generic: config-armv7-generic-merged temp-arm-generic
	perl merge.pl $^ > $@

temp-armv7: config-armv7-merged temp-armv7-generic
	perl merge.pl $^ > $@

temp-armv7-lpae: config-armv7-lpae-merged temp-armv7-generic
	perl merge.pl $^ > $@

temp-x86-32: config-x86-32-generic-merged config-x86-generic-merged
	perl merge.pl $^  > $@

temp-x86-32-generic: temp-x86-32 temp-generic
	perl merge.pl $^  > $@

temp-x86-debug-generic: temp-x86-32 temp-debug-generic
	perl merge.pl $^  > $@

temp-x86-64: config-x86_64-generic-merged config-x86-generic-merged
	perl merge.pl $^  > $@

temp-x86_64-generic: temp-x86-64 temp-generic
	perl merge.pl $^  > $@

temp-x86_64-debug-generic: temp-x86-64 temp-debug-generic
	perl merge.pl $^  > $@

temp-powerpc-generic: config-powerpc-generic-merged temp-generic
	perl merge.pl $^  > $@

temp-powerpc-debug-generic: config-powerpc-generic-merged temp-debug-generic
	perl merge.pl $^  > $@

temp-powerpc32-generic: config-powerpc32-generic-merged temp-powerpc-generic
	perl merge.pl $^  > $@

temp-powerpc64-generic: config-powerpc64-merged temp-powerpc-generic
	perl merge.pl $^ > $@

temp-s390-generic: config-s390x-merged temp-generic
	perl merge.pl $^ > $@

kernel-$(VERSION)-i686-PAE.config: config-i686-PAE-merged temp-x86-32-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-PAEdebug.config: config-i686-PAE-merged temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686.config: /dev/null temp-x86-32-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-debug.config: /dev/null temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-x86_64.config: /dev/null temp-x86_64-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-debug.config: /dev/null temp-x86_64-debug-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-ppc64.config: /dev/null temp-powerpc64-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppc64-debug.config: temp-powerpc64-generic temp-powerpc-debug-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppc64p7.config: config-powerpc64p7-merged temp-powerpc64-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-s390x.config: config-s390x-merged temp-s390-generic
	perl merge.pl $^ s390 > $@

kernel-$(VERSION)-armv7hl.config: /dev/null temp-armv7
	perl merge.pl $^ arm > $@

kernel-$(VERSION)-armv7hl-lpae.config: /dev/null temp-armv7-lpae
	perl merge.pl $^ arm > $@

kernel-$(VERSION)-ppc.config: /dev/null temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppc-smp.config: config-powerpc32-smp-merged temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppcnf.config: config-ppcnf-generic-merged temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppcnf-debug.config: config-ppcnf-debug-merged temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@

kernel-$(VERSION)-ppc476.config: config-ppc476-generic-merged temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@
